### ISSUE TITLE
Please add Russian translation

### ISSUE THREAD

**Issue by lex1975** [RimWorldMod/Tech-Advancing#16]
[Russian.zip](https://github.com/RimWorldMod/Tech-Advancing/files/3907916/Russian.zip)
Russian translation for TechAdvancing-1.0 (17-10-2019)
I don’t know how to pull request, sorry

**Comment by GHXX** [comment]
Okay, the thing is, when submitting stuff via a pullrequest then background checks are run to make sure that the translation xml-file is formatted properly.

Firstly go to https://github.com/RimWorldMod/Tech-Advancing
Then click on "Create new file" below the green bar that you can see in the middle of the screen.
Paste "TechAdvancing/Languages/Russian/Keyed/Russian.xml" as the file name; This will create some additional folders.
The next step is pasting in your file contents (the xml data)
After that enter a commit message and click "Propose new file"
When you clicked that it will show a screen saying "Comparing changes"
Just click on "Create Pull Request" and you should be able to create one.

**Comment by GHXX** [comment]
Closing this one due to inactivity, feel free to add a translation via a pullrequest.
